name: Icon Review

on:
  pull_request:
    paths:
      - 'icons/*.svg'

jobs:
  icon-review:
    name: Icon Review
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Review SVG files 🔍
        run: |
          svgFiles=$(git diff origin/${{ env.TARGET_BRANCH }} --diff-filter=ACMRTUX  --name-only | grep '.svg$')
          npx svg-icon-review ${svgFiles}

      - name: Post previews in PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const pngFilePath = './preview.png';

            const data = fs.readFileSync(pngFilePath);
            const base64Data = data.toString('base64');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `![Generated PNG](data:image/png;base64,${base64Data})`
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
